### ISSUE TITLE
MeetUp TODO #21

### ISSUE THREAD

**Issue by tom-256** [kanazawa-js/kanazawa-js.github.io#91]
## 日程
6月
- 2022/6/25  14:00 ~ 17:00

## 会場

- Discord（オンライン）
  - Slack の #meetup でチャット
  - Discord の もくもく部屋（ボイスチャンネル） でボイチャする

## 開催までのTODO

うえから順番にやる

### 3週間前

- [x] Connpassイベントページの作成
  - 前回のイベントをコピーして生成する
- [ ] Connpassで1週間前と1日前のメッセージを投稿予約する
  - connpassのメッセージは[お知らせ文言テンプレ](https://github.com/kanazawa-js/community-page/wiki/%E3%81%8A%E7%9F%A5%E3%82%89%E3%81%9B%E6%96%87%E8%A8%80%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC)を参考に
- [ ] コミュニティページの再デプロイ
  - conppassのイベントページを公開後、vercelの`kanazawa-js.github.io`を再デプロイする
- [ ] Slackの#generalなて次回イベントの通知をする
  - [お知らせ文言テンプレ](https://github.com/kanazawa-js/community-page/wiki/%E3%81%8A%E7%9F%A5%E3%82%89%E3%81%9B%E6%96%87%E8%A8%80%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC)を参考に
- [ ] [Buffer](https://publish.buffer.com/profile/5f44c0bf8c68015ea35d9413/tab/queue)でTwitterPostをスケジューリング（3週間前・2週間前・1週間前・前日・当日）
  - 告知内容は[お知らせ文言テンプレ](https://github.com/kanazawa-js/community-page/wiki/%E3%81%8A%E7%9F%A5%E3%82%89%E3%81%9B%E6%96%87%E8%A8%80%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC)を参考に

## 当日

- [ ] イベントのファシリテート対応
  - [こちらを確認しながら進行する！](https://github.com/kanazawa-js/community-page/wiki/%E3%83%95%E3%82%A1%E3%82%B7%E3%83%AA%E3%83%86%E3%83%BC%E3%83%88%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC)

**Comment by tom-256** [comment]
これの気になる発表を見る＆語る会
- https://techfeed.io/events/techfeed-conference-2022

**Comment by kentaro-m** [comment]
- 今「学び直し」が熱い！
     - ReactやTypeScriptなどしばらく触らなかった間のアップデートに追従できてない
     - いきなり業務で触り始めて体系的な学習ができてなかった

**Comment by tom-256** [comment]
- vite
- ブルーベリー本

**Comment by kentaro-m** [comment]
- State of JSをみんなで見よう会
-

**Comment by tom-256** [comment]
https://2021.stateofjs.com/en-US/

**Comment by kentaro-m** [comment]
- Frontend Developer Roadmapをみんなで見よう会

**Comment by tom-256** [comment]
Node.js18
https://shisama.hatenablog.com/entry/2022/04/20/011103

**Comment by tom-256** [comment]
話すのは事前に周知しておけば気にする必要なさそう
gather使っても良さそう

**Comment by kentaro-m** [comment]
@yu-kgr @tom-256 

## Connpass公開までのTODO
- [ ] 開催日時を確定させる
- [ ] 内容を確定させる
- [ ] コミュニケーションツール (Gather) を使うかどうかを確認する

**Comment by yu-kgr** [comment]
開催日時6/7はtypoです？

**Comment by yu-kgr** [comment]
あ、開催日時を確定させるのか6/7ってことか把握

**Comment by kentaro-m** [comment]
@yu-kgr 
6/25 (土) で開催したいのですが、皆川さんにも確認したいと思っており、その期限を6/7にしました。

**Comment by yu-kgr** [comment]
6/25確定で自分も大丈夫ですー！👍🏼

**Comment by kentaro-m** [comment]
> コミュニケーションツール (Gather) を使うかどうかを確認する

Gather使ってみる

**Comment by kentaro-m** [comment]
@tom-256 @yu-kgr 

> 内容を確定させる
> 今のところ有力なのは、通常どおりにもくもく会にして、途中何らかのテーマを決めて、雑談する機会をもうける
> ビルドツール or State of JS or Frontend Developer Roadmap

内容どうしましょう？もくもく会にして、途中で雑談挟む形にしますか。

テーマ例 (がちがちに固める必要なし)
「最近気になっている技術」
「最近ハマった問題」
「最近読んだ技術書」
「近況の共有」

--- 

某氏よりアドバイスをもらった内容の共有

コミュニティとして作りたい空気感をイベント名に反映させればよいのではというご意見

一例) 
- Kanazawa.js もくもく会
     -  各々がもくもく作業していて集中している感じ
- Kanazawa.js わいわい開発会
     -  各々がコミュニティをとりながら、何かを開発している感じ

**Comment by tom-256** [comment]
Kanazawa.js わいわい開発会にしましょうか
スライド無しでテーマ例の中からどれか5分程度話して、周りの人がその議題についてリアクションするみたいなイメージでどうでしょうか

**Comment by yu-kgr** [comment]
いちど試してみるに関しては賛成ですー。

**Comment by kentaro-m** [comment]
いいとおもいます
